# Generated by Django 4.2.26 on 2025-11-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_unit_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationoption',
            name='legacy_addon_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='legacy_ingredient_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='legacy_menu_item_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
