# Generated by Django 4.2.26 on 2025-11-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customizationoption_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizationoption',
            name='unit',
        ),
    ]
