# Generated by Django 4.2.26 on 2025-11-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_customizationoption_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='available_customizations',
        ),
    ]
