# Generated by Django 4.2.26 on 2025-12-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
